POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Mar",
    "email": "martorre@gmail.com",
    "password": "14555508"
}

###
PUT http://localhost:5000/api/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViZWM2NDkyY2RiZmNmYTYzMDY2MDciLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJ0b3JyZUBnbWFpbC5jb20iLCJzdGF0dXMiOjAsImlhdCI6MTc0MzUxNDcyNCwiZXhwIjoxNzQzNTIxOTI0fQ.LdBrz8idZxVJO74QSZTo9C10wbbqy3M8-hAyv7zS_24

{
    "code": "347092"
}

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "gsp@gmail.com",
    "password": "14344508"
}

###
POST http://localhost:5000/api/email/send-email
Content-Type: application/json

{
    "to": "martorressearle@gmail.com",
    "subject": "Test Email",
    "text": "This is a test email." 
}

POST http://localhost:3000/api/send-email
Content-Type: application/json

{
    "email": "el@gmail.com",
    "password": "14344508"
}
