
//registrar usuario
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Mar",
    "email": "mar@gmail.com",  
    "password": "14555508"
}

//validar usuario
###
PUT http://localhost:5000/api/users/validation            
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

{
    "emailCode": "846244"
}

//completar registro
###
PUT http://localhost:5000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

{
    "name": "Mar",
    "lastname": "Torre",
    "nif": "837004"
}

//login
###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "mar@gmail.com",
    "password": "14555508"
}


//añadir direccion
###
PATCH http://localhost:5000/api/users/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

{
    "address": {
        "street": "Calle de la Constitución",
        "number": "1",
        "city": "Madrid",
        "province": "Madrid",
        "postalCode": "28001",
        "country": "Spain"
    }

}

//añadir empresa
###
PATCH http://localhost:5000/api/users/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

{
    "company": {
        "name": "Empresa de prueba",
        "address": "Calle San Vicente",
        "number": "5",
        "city": "Las Rozas",
        "province": "Madrid",
        "postalCode": "28001",
        "country": "Spain"
    }
}

//añadir logo
###
PATCH http://localhost:5000/api/users/logo
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

--boundary123
Content-Disposition: form-data; name="image"; filename="logoUser.jpeg"
Content-Type: image/jpeg

< ./logoUser.jpeg
--boundary123--

//obtener usuario
###
GET http://localhost:5000/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

//eliminar usuario
###

DELETE http://localhost:5000/api/users?soft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViZWM2NDkyY2RiZmNmYTYzMDY2MDciLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJ0b3JyZUBnbWFpbC5jb20iLCJzdGF0dXMiOjAsImlhdCI6MTc0MzUxNDcyNCwiZXhwIjoxNzQzNTIxOTI0fQ.LdBrz8idZxVJO74QSZTo9C10wbbqy3M8-hAyv7zS_24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViZWM2NDkyY2RiZmNmYTYzMDY2MDciLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJ0b3JyZUBnbWFpbC5jb20iLCJzdGF0dXMiOjAsImlhdCI6MTc0MzUxNDcyNCwiZXhwIjoxNzQzNTIxOTI0fQ.LdBrz8idZxVJO74QSZTo9C10wbbqy3M8-hAyv7zS_24

//solicitar codigo de recuperacion
###
POST http://localhost:5000/api/users/recovery-code
Content-Type: application/json

{
    "email": "mttss@gmail.com"
}

//cambiar contraseña
###
PATCH http://localhost:5000/api/users/recovery-password
Content-Type: application/json

{
    "email": "mttss@gmail.com",
    "recoveryCode": "466453",
    "password": "14533308"
}

###

POST http://localhost:5000/api/users/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VjNjYyODdjMzYxZDgxZDQ0Y2JhNTEiLCJyb2xlIjpbInVzZXIiXSwiZW1haWwiOiJtYXJAZ21haWwuY29tIiwic3RhdHVzIjowLCJpYXQiOjE3NDM1NDU4OTYsImV4cCI6MTc0MzU1MzA5Nn0.yrx61gheBPYVwbfpdFcVpFLLwu3hC-hOUz9mKJR-bsg

{
    "email": "mal@gmail.com"
}


//mandar email
###
POST http://localhost:5000/api/email/send-email
Content-Type: application/json

{
    "to": "martorressearle@gmail.com",
    "subject": "Test Email",
    "text": "This is a test email." 
}


